"""patient portal: consent scopes, audit events, feedback, record attribution, user profile

Revision ID: c125e8449d3d
Revises: 019290090071
Create Date: 2026-01-16 20:56:09.866257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c125e8449d3d'
down_revision = '019290090071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table('audit_events'):
        op.create_table('audit_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('actor_id', sa.Integer(), nullable=True),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('doctor_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(length=128), nullable=False),
        sa.Column('entity', sa.String(length=128), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['doctor_id'], ['doctors.user_id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.user_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('audit_events', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
            batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_audit_events_doctor_id'), ['doctor_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_audit_events_entity'), ['entity'], unique=False)
            batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_audit_events_patient_id'), ['patient_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_audit_events_timestamp'), ['timestamp'], unique=False)

    if not inspector.has_table('doctor_feedback'):
        op.create_table('doctor_feedback',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('doctor_id', sa.Integer(), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['doctor_id'], ['doctors.user_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.user_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('doctor_id', 'patient_id', name='uq_feedback_doctor_patient')
        )
        with op.batch_alter_table('doctor_feedback', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_doctor_feedback_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_doctor_feedback_doctor_id'), ['doctor_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_doctor_feedback_patient_id'), ['patient_id'], unique=False)

    consent_cols = {c['name'] for c in inspector.get_columns('consents')}
    with op.batch_alter_table('consents', schema=None) as batch_op:
        if 'can_view_history' not in consent_cols:
            batch_op.add_column(sa.Column('can_view_history', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        if 'can_add_record' not in consent_cols:
            batch_op.add_column(sa.Column('can_add_record', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    mr_cols = {c['name'] for c in inspector.get_columns('medical_records')}
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        if 'appointment_id' not in mr_cols:
            batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=True))
        if 'created_by_user_id' not in mr_cols:
            batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))

        existing_mr_indexes = {ix.get('name') for ix in inspector.get_indexes('medical_records')}
        if batch_op.f('ix_medical_records_appointment_id') not in existing_mr_indexes:
            batch_op.create_index(batch_op.f('ix_medical_records_appointment_id'), ['appointment_id'], unique=False)
        if batch_op.f('ix_medical_records_created_by_user_id') not in existing_mr_indexes:
            batch_op.create_index(batch_op.f('ix_medical_records_created_by_user_id'), ['created_by_user_id'], unique=False)

        existing_mr_fks = {fk.get('referred_table') + ':' + ','.join(fk.get('constrained_columns', [])) for fk in inspector.get_foreign_keys('medical_records')}
        if 'users:created_by_user_id' not in existing_mr_fks:
            batch_op.create_foreign_key('fk_medical_records_created_by_user_id_users', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
        if 'appointments:appointment_id' not in existing_mr_fks:
            batch_op.create_foreign_key('fk_medical_records_appointment_id_appointments', 'appointments', ['appointment_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_medical_records_appointment_id_appointments', type_='foreignkey')
        batch_op.drop_constraint('fk_medical_records_created_by_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_medical_records_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_medical_records_appointment_id'))
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('appointment_id')

    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_column('can_add_record')
        batch_op.drop_column('can_view_history')

    with op.batch_alter_table('doctor_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_feedback_patient_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_feedback_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_feedback_created_at'))

    op.drop_table('doctor_feedback')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_events_patient_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity'))
        batch_op.drop_index(batch_op.f('ix_audit_events_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
